Task40
olgamorozova1/Selenium pull request #2
Opened 2020-10-29 21:10 UTC by olgamorozova1

2020-11-05 09:05 UTC, KirillKarpov commented
The good practice is to end test classes name with *Test.
As example Alert -> AlertTest
Can you update all classes under package test

2020-11-05 10:24 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/task9/TablePage.java
> +    public List<EmployeeSelectedInfo> selectEmployeeByAgeAndSalary(WebDriver driver, List<EmployeeAllInfo> employeeAllInfo) {
Do you need driver there ?

2020-11-05 10:24 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/task9/EmployeeAllInfo.java
> +    private int Salary;
Should it start uppercase letter ?

2020-11-05 10:24 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/task9/EmployeeSelectedInfo.java
> +public class EmployeeSelectedInfo extends EmployeeInfo {
No need in this class if you will do EmployeInfo class not abstract

2020-11-05 10:24 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/task9/EmployeeInfo.java
> +public abstract class EmployeeInfo {
I don't think it should be abstract, as it is the object with fields that you would like to get after filtering

2020-11-05 10:24 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/Multiselect.java
> +        System.out.println(expectedSelectedValues);
Do you need System.out there?

2020-11-05 19:38 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/Alert.java
> +        WebElement button = driver.findElement(By.xpath("(//button[@class='btn btn-default btn-lg'])[1]"));
id='confirm-demo' relates to another tag 'p'. I can find this button with such xpath using id: '//p[@id='confirm-demo']//preceding-sibling::button'. Is it fine or I do not see easier way?)

2020-11-05 21:57 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/Alert.java
> +package org.issoft.automation.test;
Sure, classes are updated.

2020-11-05 21:57 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/Alert.java
> +    public void setUp() {
New class is created.

2020-11-05 21:58 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/Alert.java
> +        WebElement button = driver.findElement(By.xpath("(//button[@class='btn btn-default btn-lg'])[1]"));
Variables are moved on class level.

2020-11-05 21:58 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/Alert.java
> +        driver.switchTo().alert().accept();
Fixed

2020-11-05 21:59 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/WaitForUser.java
> +        Assertions.assertEquals(true, userPhotoIsDisplayed );
Fixed

2020-11-05 22:00 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/RefreshPageBeforeDownloadComplete.java
> +        }
Used ExpectedConditions.textMatches method.

2020-11-05 22:01 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/task9/TablePage.java
> +public class TablePage {
Yes, new constructor allowed me to get rid of driver param. Fixed.

2020-11-05 22:02 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/task9/TablePage.java
> +        List<EmployeeAllInfo> employeeAllInfo = new ArrayList<>();
Fixed.

2020-11-05 22:02 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/task9/TablePage.java
> +    public List<EmployeeSelectedInfo> selectEmployeeByAgeAndSalary(WebDriver driver, List<EmployeeAllInfo> employeeAllInfo) {
No, removed.

2020-11-05 22:03 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/task9/EmployeeAllInfo.java
> +    private int Salary;
No, all variables should start with lowercase letter, fixed

2020-11-05 22:03 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/task9/EmployeeSelectedInfo.java
> +public class EmployeeSelectedInfo extends EmployeeInfo {
Class is deleted.

2020-11-05 22:04 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/task9/EmployeeInfo.java
> +public abstract class EmployeeInfo {
Yes, agree, fixed.

2020-11-05 22:04 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/Multiselect.java
> +        System.out.println(expectedSelectedValues);
No, removed.

2020-11-07 14:50 UTC, KirillKarpov requested changes

2020-11-07 14:50 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/AlertTest.java
> +//    private WebElement buttonClickForPromptText = driver.findElement(By.xpath("//p[@id='prompt-demo']//preceding-sibling::button"));
Do you need it ?

2020-11-07 14:50 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/RefreshPageBeforeDownloadCompleteTest.java
> +        }
You need to add assertion. Otherwise it is not a test

2020-11-07 14:50 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/SelectDataFromTableTest.java
> +        List<EmployeeInfo> selectedEmployees = tablePage.selectEmployeeByAgeAndSalary(allInfoAboutEmployee);
You need to add assertion. Otherwise it is not a test

2020-11-07 14:50 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/MultiselectTest.java
> +        System.out.println(expectedSelectedValues);
Wasn't removed :)

2020-11-07 15:46 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/AlertTest.java
> +//    private WebElement buttonClickForPromptText = driver.findElement(By.xpath("//p[@id='prompt-demo']//preceding-sibling::button"));
No, removed.

2020-11-07 15:46 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/RefreshPageBeforeDownloadCompleteTest.java
> +        }
Added assertion.

2020-11-07 15:46 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/SelectDataFromTableTest.java
> +        List<EmployeeInfo> selectedEmployees = tablePage.selectEmployeeByAgeAndSalary(allInfoAboutEmployee);
Added assertion.

2020-11-07 15:46 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/MultiselectTest.java
> +        System.out.println(expectedSelectedValues);
Sorry, now it is removed)

2020-11-07 16:22 UTC, KirillKarpov approved these changes

2020-11-08 09:20 UTC, merged