Task 60 - Page Object pattern
olgamorozova1/Selenium pull request #3
Opened 2020-11-08 20:30 UTC by olgamorozova1

2020-11-14 05:49 UTC, KirillKarpov requested changes

2020-11-14 05:49 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/MainPage.java
>      }
I don't see a big need to create method that has only one string of the code.
No need to delete them, but do you get any benefit of having them?

2020-11-14 05:49 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/MainPage.java
> +    public void fillLoginFields(String login, String password) {
The method doesn't only fill fields. It is also click button :)

2020-11-14 05:49 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/MainPage.java
> +    }
Same comment about, do you get any benefit of having such methods?

2020-11-14 05:49 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/LoginAndLogoutTest.java
> +        mainPage.login("seleniumtests@tut.by", "123456789zxcvbn").logout();
I don't see assert :)

2020-11-14 05:49 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/TestBase.java
> +        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
In the test you explicit wait and there you are setting implict. 
From official selenium site (https://www.selenium.dev/documentation/en/webdriver/waits/):
_Warning: Do not mix implicit and explicit waits. Doing so can cause unpredictable wait times. For example, setting an implicit wait of 10 seconds and an explicit wait of 15 seconds could cause a timeout to occur after 20 seconds._

2020-11-14 16:12 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/MainPage.java
>      }
As I cannot refer private varibles I have created all necessary methods which I can use in other classes. Now it increase only readability of code (at least in my opinion :). Also it allows me use this methods in case I need it in my test separately, not only as part of login method.

2020-11-14 16:12 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/MainPage.java
> +    public void fillLoginFields(String login, String password) {
Renamed.

2020-11-14 16:12 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/MainPage.java
> +    }
Answer is above.

2020-11-14 16:13 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/LoginAndLogoutTest.java
> +        mainPage.login("seleniumtests@tut.by", "123456789zxcvbn").logout();
Sorry, assert is added. Will try not to forget about them next time.

2020-11-14 16:14 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/TestBase.java
> +        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
Removed implicit wait.

2020-11-16 08:03 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/MainPage.java
>      }
Let's discuss in skype

2020-11-16 08:22 UTC, KirillKarpov approved these changes

2020-11-16 16:35 UTC, merged