Task 60 - Page Factory pattern
olgamorozova1/Selenium pull request #4
Opened 2020-11-08 21:40 UTC by olgamorozova1

2020-11-14 05:54 UTC, KirillKarpov requested changes

2020-11-14 05:54 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/LoginAndLogoutTest.java
> +    MainPage mainPage = PageFactory.initElements(driver, MainPage.class);
Init of elements should happen on Page Object class, but not in the test

2020-11-14 05:54 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/MainPage.java
>      }
Same question as in PR 3, Do you getting any benefit from those methods?

2020-11-14 05:54 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/LoginAndLogoutTest.java
> +        mainPage.logout();
Looks like you missed assert :)

2020-11-15 07:45 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/LoginAndLogoutTest.java
> +    MainPage mainPage = PageFactory.initElements(driver, MainPage.class);
Moved initElements to constructor of MainPage class.

2020-11-15 07:48 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/page/MainPage.java
>      }
As I cannot refer private varibles I have created all necessary methods which I can use in other classes. Now it increase only readability of code (at least in my opinion :). Also it allows me use this methods in case I need it in my test separately, not only as part of login method. Also I saw such approach in examples on different resources as additional level of abstraction...Let me please know if it is bad approach and I will not use it

2020-11-15 07:48 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/LoginAndLogoutTest.java
> +        mainPage.logout();
Sorry, assert is added.

2020-11-16 08:03 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/page/MainPage.java
>      }
Let's discuss it by skype. You are moving in the right direction. I would like to provide some hints how to reduce number of methods.

2020-11-16 08:23 UTC, KirillKarpov approved these changes

2020-11-16 17:29 UTC, merged