Task 70
olgamorozova1/Selenium pull request #5
Opened 2020-11-10 06:46 UTC by olgamorozova1

2020-11-14 06:05 UTC, KirillKarpov requested changes

2020-11-14 06:05 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/TestBase.java
> +            FileUtils.moveFile(screenshot, new File("./src/main/resources/" + fileName));
Two comments to the path "./src/main/resources/"
1) If you would like to use resources folder, it is better not to put everything on the root level. The good option is create folder with screenshots.
2) Using resources is not the optimal option. I suggest to use target folder , which created during code compilation

2020-11-15 08:02 UTC, olgamorozova1 commented on src/main/java/org/issoft/automation/test/TestBase.java
> +            FileUtils.moveFile(screenshot, new File("./src/main/resources/" + fileName));
I created new folder for screenshots in the target folder. Why do we pick up target? I think it is not good idea to mix code and temporary files so I'm agree it should not be resources, but why is it target but no separate folder in the root?

2020-11-16 07:16 UTC, KirillKarpov commented on src/main/java/org/issoft/automation/test/TestBase.java
> +            FileUtils.moveFile(screenshot, new File("./src/main/resources/" + fileName));
It is not forbidden to create any folder on the root level. But it is not good practice.

The target folder used by other libraries to put files that were generated during code execution. It is like a default place for all of them.  As for us (automation engineers :) ) the interesting libraries is JUnit/TestNG. It will put results of the test execution to target folder. That is why it looks native to put screenshots to the same folder

2020-11-16 08:23 UTC, KirillKarpov approved these changes

2020-11-16 16:33 UTC, merged